# Generated by Django 3.2.21 on 2023-11-28 11:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20231127_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignees',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='project_name',
            field=models.CharField(default='rukundo', max_length=255),
            preserve_default=False,
        ),
    ]
