# Generated by Django 3.2.21 on 2023-11-28 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_task_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignees',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
